### ISSUE TITLE
gnmi get for out-pkts failing in OTG with ixia HW

### ISSUE THREAD

**Issue by bkreddy143** [open-traffic-generator/ixia-c#134]
seeing value not present error while running feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetin_test script with OTG on ixia HW chassis. 

Where as same script works fine with KNE . 

    google_discovery_protocol_packetin_test.go:181: GetAll(t) on {ate: ATE{Dims:Dims{Name:127.0.0.1:40051 Vendor:IXIA HardwareModel: SoftwareVersion: Ports:map[port1:Port{Name:xxxxxx;10;1 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port2:Port{Name:135.227.241.22;10;2 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED}] CustomData:map[]}}} at /flows/flow[name=*]/state/counters/out-pkts: query "/flows/flow[name=*]/state/counters/out-pkts": value not present

**Comment by arkajyoti-cloud** [comment]
Can you please provide more logs mainly the gnmi server logs & controller logs for this issue?

**Comment by bkreddy143** [comment]
i see today it is failing due to different error in latest ixia version 
    packetin_test.go:183: TTL/HopLimit 1
=== RUN   TestPacketIn/PacketIn_to_Primary_Controller#01
    packetin_test.go:197: Start to decode packet and compare with expected packets.
--- FAIL: TestPacketIn (62.11s)
    --- PASS: TestPacketIn/PacketIn_to_Primary_Controller (0.00s)
    --- PASS: TestPacketIn/PacketIn_to_Secondary_Controller (0.00s)
    --- FAIL: TestPacketIn/PacketIn_to_Primary_Controller#01 (0.00s)
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 186 [running]:
testing.tRunner.func1.2({0xa12a420, 0xc000250f00})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0xa12a420, 0xc000250f00})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/openconfig/featureprofiles/feature/experimental/p4rt/otg_tests/traceroute_packetin_test_test.testPacketIn.func2(0xc003602ea0)
	/home/nokia/openconfig/untouched/featureprofiles/feature/experimental/p4rt/otg_tests/traceroute_packetin_test/packetin_test.go:234 +0x7c6
testing.tRunner(0xc003602ea0, 0xc001e03480)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/openconfig/featureprofiles/feature/experimental/p4rt/otg_tests/traceroute_packetin_test	64.677s
[logs-2023-07-05_132720.tar.gz](https://github.com/open-traffic-generator/ixia-c/files/11961838/logs-2023-07-05_132720.tar.gz)
