### ISSUE TITLE
bug: ipv4.header.priority.raw with ixia-hw controller

### ISSUE THREAD

**Issue by carlmontanari** [open-traffic-generator/ixia-c#180]
👋 

opening for tracking based on conversation in slack, pasting details here:

given the following metric setup for tracking ipv4 priority raw fields for phb/ecn:

```
flow.EgressPacket().Add().Ethernet()
tracking := flow.EgressPacket().Add().Ipv4()

tracking.Priority().Raw().MetricTags().Add().SetName(fmt.Sprintf("dst-phb-%d", dscpValue)).SetOffset(0).SetLength(6)

tracking.Priority().Raw().MetricTags().Add().SetName(fmt.Sprintf("dst-ecn-%d", dscpValue)).SetOffset(6).SetLength(2)
```

I received the following error when running an fp test (dp-1.14 if it matters):

```
2023-12-19 21:37:47Z span:set_config dur:00:00:05.6460755
  Exception Unable to find field 'ipv4.header.priority.raw' in packet 'ipv4'   at OTGService.ProtocolTemplates.FindField(ProtocolPacket packet, String tclId)
   at OTGService.ProtocolTemplates.ProcessEgressTracking(ProtocolPacket packet, String templateName, FlowHeader otgFlowHeader, List`1& egressTrackingTags)
   at OTGService.Flow.ProcessEgressTracking(List`1 protocolPackets, String templateName, FlowHeader flowHeader, List`1& egressTrackingTags)
   at OTGService.Flow.GetFlowTrackings(Flow flow)
   at OTGService.Flow.ConfigTraking(TrafficItem trafficItem, Flow flow)
   at OTGService.Flow..ctor(ITransactionContext context, Config config, Boolean virtualApply)
   at OTGService.ConfigService.SetConfig(SetConfigRequest request)
   at OTGService.OtgService.SetConfig(SetConfigRequest request, ServerCallContext context)
```

with the important part being `Exception Unable to find field 'ipv4.header.priority.raw' in packet 'ipv4'`

Alakendu Jana mentioned this is/was `some issue in OTG-HW side related to ipv4.header.priority.raw . We are working on it`

[Link](https://keysight.slack.com/archives/C0428HT2MLN/p1702590704369089) to the slack convo.

I should be able to reproduce easily if there's anything else needed, just holler!

**Comment by carlmontanari** [comment]
fixed in latest [release](https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.1.0-222) closing, thanks ya'll!
