### ISSUE TITLE
demo1-snappi-ixia-c program issue , need help to resolve

### ISSUE THREAD

**Issue by madhudhavala** [open-traffic-generator/ixia-c#80]
Hello community @
Thank you for providing details steps to try it out snappy with ixia-c.
This is regarding demo1-snappi-ixia-c as mentioned in https://github.com/chrispsommers/p4-guide/blob/snappi-tests2/demo1-snappi-ixia-c/README.md

I see below issue while executing the demo1 program.. Details mentioned below . Could some one suggust the right solution for this program.

**p4@p4:~/p4-guide/demo1-snappi-ixia-c$ sudo ./runptf.sh demo1-snappi.SnappiFwdTestBidirLpmRange**
P is: /home/p4/p4-guide/testlib
Starting IXia-c traffic engines and controller...
f1ffe962307bb7e1e750522cf9a7d60dccabcd2df27883422fb4ae2ebff71bd9
7e17f71d6fb6e2f5ea48dbb393951e2ff46eadda186c8927d94eef3479efa22c
bdb938552793c6fc6058cd5d9b8a8c3cc40a83c4b0c2fb08648c8a820b441db3
54bd59ada3bd82becb3c39b849c78fe7d8239091fa6695b1e85b903893e726a5
f3805b2d3456ef18c68ab23f2a7c5c22b7aef7288962cbb2e0295ff66c1713cb
/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/EGG-INFO/scripts/ptf:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using packet manipulation module: ptf.packet_scapy
File=/home/p4/p4-guide/settings.json

2022-06-14 17:32:45,586 - root - INFO - Importing platform: eth
2022-06-14 17:32:45,587 - root - DEBUG - Configuration: {'list': False, 'list_test_names': False, 'allow_user': False, 'test_spec': '', 'test_file': None, 'test_dir': 'ptf', 'test_order': 'default', 'test_order_seed': 2746, 'num_shards': 1, 'shard_id': 0, 'platform': 'eth', 'platform_args': None, 'platform_dir': '/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/ptf/platforms', 'interfaces': [(0, 0, 'veth1'), (0, 1, 'veth3'), (0, 2, 'veth5'), (0, 3, 'veth7'), (0, 4, 'veth9'), (0, 5, 'veth11'), (0, 6, 'veth13'), (0, 7, 'veth15')], 'port_info': {}, 'device_sockets': [], 'log_file': 'ptf.log', 'log_dir': None, 'debug': 'verbose', 'profile': False, 'profile_file': 'profile.out', 'xunit': False, 'xunit_dir': 'xunit', 'relax': False, 'test_params': "grpcaddr='localhost:9559';p4info='demo1.p4_16.p4rt.txt';config='demo1.p4_16.json'", 'failfast': False, 'fail_skipped': False, 'default_timeout': 2.0, 'default_negative_timeout': 0.1, 'minsize': 0, 'random_seed': None, 'disable_ipv6': False, 'disable_vxlan': False, 'disable_erspan': False, 'disable_geneve': False, 'disable_mpls': False, 'disable_nvgre': False, 'disable_igmp': False, 'disable_rocev2': False, 'qlen': 100, 'test_case_timeout': None, 'socket_recv_size': 4096, 'packet_manipulation_module': 'ptf.packet_scapy', 'port_map': {(0, 0): 'veth1', (0, 1): 'veth3', (0, 2): 'veth5', (0, 3): 'veth7', (0, 4): 'veth9', (0, 5): 'veth11', (0, 6): 'veth13', (0, 7): 'veth15'}}
2022-06-14 17:32:45,587 - root - INFO - port map: {(0, 0): 'veth1', (0, 1): 'veth3', (0, 2): 'veth5', (0, 3): 'veth7', (0, 4): 'veth9', (0, 5): 'veth11', (0, 6): 'veth13', (0, 7): 'veth15'}
2022-06-14 17:32:45,587 - root - INFO - Autogen random seed: 95877887
2022-06-14 17:32:45,588 - root - INFO - *** TEST RUN START: Tue Jun 14 17:32:45 2022
demo1-snappi.SnappiFwdTestBidirLpmRange ... 

*****************
Loading P4 Program...
***************

ERROR**

======================================================================
ERROR: demo1-snappi.SnappiFwdTestBidirLpmRange
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f8ed2ff7250>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8ed2ff7250>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/p4/p4-guide/testlib/base_test.py", line 1008, in handle
    return f(*args, **kwargs)
  File "ptf/demo1-snappi.py", line 837, in runTest
    res = self.api.set_config(self.cfg)
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 40522, in set_config
    return self._transport.send_recv(
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappicommon.py", line 28, in send_recv
    response = self._session.request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8ed2ff7250>: Failed to establish a new connection: [Errno 111] Connection refused'))

----------------------------------------------------------------------
Ran 1 test in 0.030s

FAILED (errors=1)

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests errored:
SnappiFwdTestBidirLpmRange

******************************************
Killing Ixia-C traffic engines and controller...
54bd59ada3bd
bdb938552793
7e17f71d6fb6
f1ffe962307b

**Comment by chrispsommers** [comment]
Hi Madhu, thanks for the report. Please try the p4-guide experiments using the versions listed in https://github.com/chrispsommers/p4-guide/blob/snappi-tests2/demo1-snappi-ixia-c/README.md#ptf-tests-overview (ixia-c-controller:0.0.1-1622 and ixia-c-traffic-engine:1.4.0.1). It's possible installing ":latest" is no longer compatible. If you get it working with those versions, please feel free to file a PR against the p4-guide README showing the correct instructions to download the right tags. Thanks!

**Comment by madhudhavala** [comment]
Hi Chris Sommers,
Thank you for your reply and notes.
Here is what i did
1) updated run_ixia-c.sh file with these below lines
CONTROLLER=ixiacom/ixia-c-controller:0.0.1-1622
ENGINE=ixiacom/ixia-c-traffic-engine:1.4.0.1
2) ran sudo ./runptf.sh demo1-snappi.SnappiFwdTestBidirLpmRange 
CUrrently iam seeing issue in File "ptf/demo1-snappi.py", line 333, in setUp 
Here are the logs
p4@p4:~/p4-guide/demo1-snappi-ixia-c$ sudo ./runptf.sh demo1-snappi.SnappiFwdTestBidirLpmRange
P is: /home/p4/p4-guide/testlib
Starting IXia-c traffic engines and controller...
af92fb209490db63005720a8aac60c22cd46b8ae2e39ec484e8cac3aa1ad699b
a212b212beebe13c6f405382b82adc83a13930902da6c4fe4cc1ad53b6d49331
f4cbc9e3ccf135a524b33500817269da4cbd61c13c67f01d48f45bf4753a386d
c0d4292c8d8fadf3cf48478a8bac6539d68e989ffed81aca2f9b1e26d2e1742e
bdd5a036a29bf45227dd7f50e174971917bc92de04cca32241d7d5fefb70a7b0
/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/EGG-INFO/scripts/ptf:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using packet manipulation module: ptf.packet_scapy
File=/home/p4/p4-guide/settings.json

2022-06-15 19:23:17,947 - root - INFO - Importing platform: eth
2022-06-15 19:23:17,948 - root - DEBUG - Configuration: {'list': False, 'list_test_names': False, 'allow_user': False, 'test_spec': '', 'test_file': None, 'test_dir': 'ptf', 'test_order': 'default', 'test_order_seed': 2746, 'num_shards': 1, 'shard_id': 0, 'platform': 'eth', 'platform_args': None, 'platform_dir': '/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/ptf/platforms', 'interfaces': [(0, 0, 'veth1'), (0, 1, 'veth3'), (0, 2, 'veth5'), (0, 3, 'veth7'), (0, 4, 'veth9'), (0, 5, 'veth11'), (0, 6, 'veth13'), (0, 7, 'veth15')], 'port_info': {}, 'device_sockets': [], 'log_file': 'ptf.log', 'log_dir': None, 'debug': 'verbose', 'profile': False, 'profile_file': 'profile.out', 'xunit': False, 'xunit_dir': 'xunit', 'relax': False, 'test_params': "grpcaddr='localhost:9559';p4info='demo1.p4_16.p4rt.txt';config='demo1.p4_16.json'", 'failfast': False, 'fail_skipped': False, 'default_timeout': 2.0, 'default_negative_timeout': 0.1, 'minsize': 0, 'random_seed': None, 'disable_ipv6': False, 'disable_vxlan': False, 'disable_erspan': False, 'disable_geneve': False, 'disable_mpls': False, 'disable_nvgre': False, 'disable_igmp': False, 'disable_rocev2': False, 'qlen': 100, 'test_case_timeout': None, 'socket_recv_size': 4096, 'packet_manipulation_module': 'ptf.packet_scapy', 'port_map': {(0, 0): 'veth1', (0, 1): 'veth3', (0, 2): 'veth5', (0, 3): 'veth7', (0, 4): 'veth9', (0, 5): 'veth11', (0, 6): 'veth13', (0, 7): 'veth15'}}
2022-06-15 19:23:17,948 - root - INFO - port map: {(0, 0): 'veth1', (0, 1): 'veth3', (0, 2): 'veth5', (0, 3): 'veth7', (0, 4): 'veth9', (0, 5): 'veth11', (0, 6): 'veth13', (0, 7): 'veth15'}
2022-06-15 19:23:17,948 - root - INFO - Autogen random seed: 82001879
2022-06-15 19:23:17,952 - root - INFO - *** TEST RUN START: Wed Jun 15 19:23:17 2022
demo1-snappi.SnappiFwdTestBidirLpmRange ... 

***************
Loading P4 Program...
***************

ERROR

======================================================================
ERROR: demo1-snappi.SnappiFwdTestBidirLpmRange
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ptf/demo1-snappi.py", line 739, in setUp
    SnappiFwdTestBase.setUp(self)
  File "ptf/demo1-snappi.py", line 333, in setUp
    **self.api = snappi.api(host='https://localhost:8080')**
TypeError: api() got an unexpected keyword argument 'host'

----------------------------------------------------------------------
Ran 1 test in 0.017s

FAILED (errors=1)

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests errored:
SnappiFwdTestBidirLpmRange

******************************************
Killing Ixia-C traffic engines and controller...
bdd5a036a29b
c0d4292c8d8f
f4cbc9e3ccf1
a212b212beeb
af92fb209490

**Comment by madhudhavala** [comment]
Hi Chris Sommers,
Good News . I foujnd the solution for this. Above issue iam seeing due to wrong snappy version that i have which is snappi 0.4.26. What you need for this demot to work is snappi-0.4.0.
So i installed sudo pip3 install snappi==0.4.0 dpkt
and re executed the runptf , now working well

p4@p4:~/p4-guide/demo1-snappi-ixia-c$ sudo ./runptf.sh demo1-snappi.SnappiFwdTestBidirLpmRange
P is: /home/p4/p4-guide/testlib
Starting IXia-c traffic engines and controller...
0ec2fe1e24277f34f6fa49bcbc6e42c54f13de19d5161a7cfef9b93ab9564b42
406c3a15fabc05565feeaff4236926a8ad5bae080746faf97d1540502fc2b28c
c0a028ea1b81106afa8687f71f7fd74f9bf8efb531e6cb59a1d0ca1754828824
1e5888b412af73414d218bd10641c1f6a41f7e61e1f8fd84e72e0860adaded81
301c9bbc7665e0539cef262610f3ae49d6b292ed67e9182f0147614b979a3213
/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/EGG-INFO/scripts/ptf:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using packet manipulation module: ptf.packet_scapy
File=/home/p4/p4-guide/settings.json

2022-06-16 04:00:02,956 - root - INFO - Importing platform: eth
2022-06-16 04:00:02,956 - root - DEBUG - Configuration: {'list': False, 'list_test_names': False, 'allow_user': False, 'test_spec': '', 'test_file': None, 'test_dir': 'ptf', 'test_order': 'default', 'test_order_seed': 2746, 'num_shards': 1, 'shard_id': 0, 'platform': 'eth', 'platform_args': None, 'platform_dir': '/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/ptf/platforms', 'interfaces': [(0, 0, 'veth1'), (0, 1, 'veth3'), (0, 2, 'veth5'), (0, 3, 'veth7'), (0, 4, 'veth9'), (0, 5, 'veth11'), (0, 6, 'veth13'), (0, 7, 'veth15')], 'port_info': {}, 'device_sockets': [], 'log_file': 'ptf.log', 'log_dir': None, 'debug': 'verbose', 'profile': False, 'profile_file': 'profile.out', 'xunit': False, 'xunit_dir': 'xunit', 'relax': False, 'test_params': "grpcaddr='localhost:9559';p4info='demo1.p4_16.p4rt.txt';config='demo1.p4_16.json'", 'failfast': False, 'fail_skipped': False, 'default_timeout': 2.0, 'default_negative_timeout': 0.1, 'minsize': 0, 'random_seed': None, 'disable_ipv6': False, 'disable_vxlan': False, 'disable_erspan': False, 'disable_geneve': False, 'disable_mpls': False, 'disable_nvgre': False, 'disable_igmp': False, 'disable_rocev2': False, 'qlen': 100, 'test_case_timeout': None, 'socket_recv_size': 4096, 'packet_manipulation_module': 'ptf.packet_scapy', 'port_map': {(0, 0): 'veth1', (0, 1): 'veth3', (0, 2): 'veth5', (0, 3): 'veth7', (0, 4): 'veth9', (0, 5): 'veth11', (0, 6): 'veth13', (0, 7): 'veth15'}}
2022-06-16 04:00:02,956 - root - INFO - port map: {(0, 0): 'veth1', (0, 1): 'veth3', (0, 2): 'veth5', (0, 3): 'veth7', (0, 4): 'veth9', (0, 5): 'veth11', (0, 6): 'veth13', (0, 7): 'veth15'}
2022-06-16 04:00:02,957 - root - INFO - Autogen random seed: 32157458
2022-06-16 04:00:02,961 - root - INFO - *** TEST RUN START: Thu Jun 16 04:00:02 2022
demo1-snappi.SnappiFwdTestBidirLpmRange ... 

***************
Loading P4 Program...
***************

Send packet prior to configuring tables, verify packets are dropped...
Starting capture on ports ['port1', 'port2'] ...
Starting traffic
Sleep 10 secs Wait for P4 pipeline to process all packets
10...
9...
8...
7...
6...
5...
4...
3...
2...
1...
Fetching all port stats ...
Fetching all flow stats ...

Port Stats
--------------------------------------------------------------------------------------------------------------
           Port      Tx Frames       Tx Bytes      Rx Frames       Rx Bytes         Tx FPS         Rx FPS
          port1            512          51200              0              0              0              0
          port2            512          51200              0              0              0              0
--------------------------------------------------------------------------------------------------------------


Flow Stats
---------------------------------------------------------------------------------------------------------
                Flow           Rx Frames            Rx Bytes      Frames Rx Rate            Transmit
             port1-2                   0                   0                   0             stopped
             port2-1                   0                   0                   0             stopped
---------------------------------------------------------------------------------------------------------


Fetching all port stats ...
Fetching all flow stats ...

Port Stats
--------------------------------------------------------------------------------------------------------------
           Port      Tx Frames       Tx Bytes      Rx Frames       Rx Bytes         Tx FPS         Rx FPS
          port1            512          51200              0              0              0              0
          port2            512          51200              0              0              0              0
--------------------------------------------------------------------------------------------------------------


Flow Stats
---------------------------------------------------------------------------------------------------------
                Flow           Rx Frames            Rx Bytes      Frames Rx Rate            Transmit
             port1-2                   0                   0                   0             stopped
             port2-1                   0                   0                   0             stopped
---------------------------------------------------------------------------------------------------------


Fetching capture from port port1
Verifying empty capture from port port1
Fetching capture from port port2
Verifying empty capture from port port2
Send packet after configuring tables, verify captured packets byte-by-byte...
Starting capture on ports ['port1', 'port2'] ...
Starting traffic
Sleep 10 secs Wait for P4 pipeline to process all packets
10...
9...
8...
7...
6...
5...
4...
3...
2...
1...

                                                                             
Waiting for stats to be as expected ...                                      
Fetching all port stats ...                                                  
Fetching all flow stats ...
Fetching all port stats ...
Fetching all flow stats ...
Done waiting for stats to be as expected
Fetching all port stats ...
Fetching all flow stats ...

Port Stats
--------------------------------------------------------------------------------------------------------------
           Port      Tx Frames       Tx Bytes      Rx Frames       Rx Bytes         Tx FPS         Rx FPS
          port1            512          51200            256          25600              0              0
          port2            512          51200            256          25600              0              0
--------------------------------------------------------------------------------------------------------------


Flow Stats
---------------------------------------------------------------------------------------------------------
                Flow           Rx Frames            Rx Bytes      Frames Rx Rate            Transmit
             port1-2                 256               25600                   0             stopped
             port2-1                 256               25600                   0             stopped
---------------------------------------------------------------------------------------------------------


Fetching all port stats ...
Fetching all flow stats ...

Port Stats
--------------------------------------------------------------------------------------------------------------
           Port      Tx Frames       Tx Bytes      Rx Frames       Rx Bytes         Tx FPS         Rx FPS
          port1            512          51200            256          25600              0              0
          port2            512          51200            256          25600              0              0
--------------------------------------------------------------------------------------------------------------


Flow Stats
---------------------------------------------------------------------------------------------------------
                Flow           Rx Frames            Rx Bytes      Frames Rx Rate            Transmit
             port1-2                 256               25600                   0             stopped
             port2-1                 256               25600                   0             stopped
---------------------------------------------------------------------------------------------------------


Fetching capture from port port2
Comparing 256 expected pkts to 256 captured pkts
Fetching capture from port port1
Comparing 256 expected pkts to 256 captured pkts
ok

----------------------------------------------------------------------
Ran 1 test in 27.922s

OK
Killing Ixia-C traffic engines and controller...
301c9bbc7665
1e5888b412af
c0a028ea1b81
406c3a15fabc
0ec2fe1e2427

**Comment by chrispsommers** [comment]
Awesome! I'm so glad to hear this! If there are any improvements you think the README's need please submit a PR or attach a replacement file in the ixia-c Slack channel. Please realize the model and APIs have changed somewhat in the last year so this example is a bit "long in the tooth." You might want to follow newer examples to get the up to date usage. If you figure out what changes are needed in this example project feel free to submit a PR or whatever. Also pretty soon there will be a nice project in the https://github.com/Azure/DASH repo using ixia-c, by coincidence it also uses bmv2 but in a different application. Stay in touch with me to learn about it.

If you feel this issue is resolved, please close it. Thanks!
