### ISSUE TITLE
Update documentation with WSL (Windows Subsystem for Linux) support info

### ISSUE THREAD

**Issue by bortok** [open-traffic-generator/ixia-c#92]
If someone tries to run ixia-c on WSL (Windows Subsystem for Linux) it won't be successful, with symptoms like these on `set_config`. Let's update our documentation with a statement about WSL support.
```
2022-08-01 19:54:36 [snappi.snappi] [WARNING] Certificate verification is disabled
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7feb4c1c5ee0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb4c1c5ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ixia-c/snappi-tests/scripts/quickstart_snappi.py", line 22, in <module>
    api.set_config(config)
  File "/home/koehlerd/.local/lib/python3.8/site-packages/snappi/snappi.py", line 69263, in set_config
    return self._transport.send_recv(
  File "/home/koehlerd/.local/lib/python3.8/site-packages/snappi/snappi.py", line 151, in send_recv
    response = self._session.request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb4c1c5ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by yennym3** [comment]
@bortok I am trying to run this test (python3 scripts/quickstart_snappi.py) and I am getting the error you mentioned (ConnectionRefusedError: [Errno 111] Connection refused), have you found a solution for this? .

**Comment by bortok** [comment]
@yennym3 most likely caused by change in default TCP port `ixia-c-controller` listens on. It is now `TCP/8443`

**Comment by yennym3** [comment]
> @yennym3 most likely caused by change in default TCP port listens on. It is now `ixia-c-controller``TCP/8443`

Modifying the port to 8443, the error persists: 

`2023-06-05 07:47:38 [snappi.snappi] [WARNING] Certificate verification is disabled
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connection.py", line 200, in _new_conn
    sock = connection.create_connection(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connection.py", line 604, in connect
    self.sock = sock = self._new_conn()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connection.py", line 215, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0e92b1f520>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e92b1f520>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart_snappi.py", line 22, in <module>
    api.set_config(config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/snappi/snappi.py", line 109337, in set_config
    return self._transport.send_recv(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/snappi/snappi.py", line 181, in send_recv
    response = self._session.request(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e92b1f520>: Failed to establish a new connection: [Errno 111] Connection refused'))
`

**Comment by bortok** [comment]
@yennym3 Would it be possible for you to join our Slack support channel so we could look into the issue? https://github.com/open-traffic-generator/ixia-c/blob/main/docs/support.md
